### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by zz217** [CasterWx/lexin#1]
运行出错，原因'data'

**Comment by CasterWx** [comment]
> 运行出错，原因'data'

secrets里面配置账号等信息了吗

**Comment by zz217** [comment]
配置了，昨天一直显示这个，今天就好了😂，不知道咋回事

**Comment by LvLaoTou** [comment]
> > 运行出错，原因'data'
> 
> 秘密里面配置账号等信息了吗

我也遇到了同样的问题
![image](https://user-images.githubusercontent.com/53200809/97959836-275f2900-1deb-11eb-8f9f-c247fa17a25d.png)

**Comment by cs81** [comment]
大佬，secrets在哪？

**Comment by CasterWx** [comment]
> 大佬，secrets在哪？
这个接口已经被封了，不用搞了

**Comment by cs81** [comment]
> > 大佬，secrets在哪？
> > 这个接口已经被封了，不用搞了

。。。。。。
