### ISSUE TITLE
无法在支付宝或者微信运动查看修改的步数

### ISSUE THREAD

**Issue by Nakolu** [CasterWx/lexin#2]
在乐心里面可以看到修改的步数，但是在支付宝运动和微信运动里看到的仍然是手机原先的步数，请问有遇到这种情况么

**Comment by HqmJoker** [comment]
> 在乐心里面可以看到修改的步数，但是在支付宝运动和微信运动里看到的仍然是手机原先的步数，请问有遇到这种情况么

我的也是这种情况，好像说是乐心app不支持同步到微信了，不知道是不是

**Comment by Cheung-yan2020** [comment]
数据同步说明里用括号解释了 必须连接设备才将设备里的步数同步到微信

**Comment by seatonjiang** [comment]
不由的联想到这是为了卖自家设备故意放出来的接口

![image](https://user-images.githubusercontent.com/57834639/97841180-45138c00-1d20-11eb-90d9-644ce9fe1150.png)

**Comment by CasterWx** [comment]
> 不由的联想到这是为了卖自家设备故意放出来的接口
> 
> ![image](https://user-images.githubusercontent.com/57834639/97841180-45138c00-1d20-11eb-90d9-644ce9fe1150.png)

确实，接口问题，不做同步了
